/* oxlint-disable jsx-a11y/prefer-tag-over-role -- Inline SVG retains its accessible title and description. */
const variables = [
  {
    symbol: 'B',
    name: 'Magnetic field',
    unit: 'T (usually expressed in µT)',
    role: 'Ambient magnetic field measured by the magnetometer',
    tone: 'field',
  },
  {
    symbol: 'm',
    name: 'Magnetic dipole moment',
    unit: 'A·m²',
    role: 'Magnetic dipole commanded to the magnetorquer',
    tone: 'moment',
  },
  {
    symbol: 'τ',
    name: 'Magnetic torque',
    unit: 'N·m',
    role: 'Magnetic torque generated by m × B',
    tone: 'torque',
  },
  {
    symbol: 'ω',
    name: 'Angular velocity',
    unit: 'rad/s · °/s',
    role: 'Current satellite rotational state affected by the torque',
    tone: 'rate',
  },
] as const;

export function AdcsVectorVisual() {
  return (
    <section className="adcs-vector-visual" aria-labelledby="adcs-vector-title">
      <header>
        <p className="eyebrow">Vectors in the satellite body frame</p>
        <h4 id="adcs-vector-title">Relationship between magnetic field, actuation command, torque and angular velocity</h4>
        <p>
          Compare the directions and key relationships of the four vectors in the same satellite body frame.
        </p>
      </header>

      <div className="adcs-vector-layout">
        <figure>
          <svg
            viewBox="0 0 520 340"
            role="img"
            aria-labelledby="adcs-vector-svg-title adcs-vector-svg-desc"
          >
            <title id="adcs-vector-svg-title">
              Vector diagram showing B, m, τ and ω in a single satellite body frame
            </title>
            <desc id="adcs-vector-svg-desc">
              From the origin, right is the magnetic field B, up is the magnetic
              moment m, upper left is the torque τ produced by the cross product
              of the two vectors, and lower left is the current angular velocity
              ω. τ is perpendicular to both m and B but is not always exactly
              opposite to ω. If m and B are parallel, the torque is zero, and
              torque along the magnetic field direction cannot be produced. The
              figure is a 2D projection and does not represent scale or the
              actual orbital attitude.
            </desc>
            <defs>
              {[
                ['axis', '#668599'],
                ['field', '#65c6ec'],
                ['moment', '#a6d86f'],
                ['torque', '#f2bd65'],
                ['rate', '#bd9cff'],
              ].map(([id, color]) => (
                <marker
                  key={id}
                  id={`arrow-${id}`}
                  markerWidth="10"
                  markerHeight="10"
                  refX="8"
                  refY="3"
                  orient="auto"
                  markerUnits="strokeWidth"
                >
                  <path d="M0,0 L0,6 L9,3 z" fill={color} />
                </marker>
              ))}
            </defs>

            <g className="vector-axes">
              <line x1="250" y1="188" x2="452" y2="188" />
              <line x1="250" y1="188" x2="250" y2="32" />
              <line x1="250" y1="188" x2="410" y2="300" />
              <text x="466" y="193">
                +x
              </text>
              <text x="239" y="22">
                +y
              </text>
              <text x="420" y="313">
                +z
              </text>
            </g>

            <circle className="vector-origin" cx="250" cy="188" r="7" />
            <text className="vector-origin-label" x="224" y="214">
              O
            </text>

            <g className="vector-arrow vector-field">
              <line x1="250" y1="188" x2="424" y2="188" />
              <text x="438" y="195">
                B
              </text>
            </g>
            <g className="vector-arrow vector-moment">
              <line x1="250" y1="188" x2="250" y2="54" />
              <text x="264" y="58">
                m
              </text>
            </g>
            <g className="vector-right-angle" aria-label="90 degrees between m and B">
              <path d="M250 166 H272 V188" />
              <text x="278" y="169">
                90°
              </text>
            </g>
            <g className="vector-arrow vector-torque">
              <line x1="250" y1="188" x2="112" y2="88" />
              <text x="86" y="82">
                τ
              </text>
              <text className="vector-relation-note" x="52" y="110">
                τ ⟂ B, m
              </text>
            </g>
            <g className="vector-arrow vector-rate">
              <line x1="250" y1="188" x2="142" y2="284" />
              <text x="112" y="303">
                ω
              </text>
            </g>

            <text className="vector-core-equation" x="324" y="92">
              τ = m × B
            </text>
          </svg>
          <figcaption>
            Teaching 2D projection · vectors are shown in the same satellite body
            frame and do not represent scale or actual attitude.
          </figcaption>
        </figure>

        <div className="adcs-variable-list" aria-label="ADCS variable meanings and units">
          {variables.map((variable) => (
            <article
              key={variable.symbol}
              className={`variable-${variable.tone}`}
            >
              <span>{variable.symbol}</span>
              <div>
                <h5>{variable.name}</h5>
                <small>{variable.unit}</small>
                <p>{variable.role}</p>
              </div>
            </article>
          ))}
        </div>
      </div>

      <div className="adcs-control-summary">
        <p>
          <span>Control objective</span>
          <strong>Reduce angular velocity magnitude |ω|</strong>
        </p>
        <p>
          Because magnetic torque is constrained by τ = m × B, it does not act
          exactly opposite to ω at every instant.
        </p>
      </div>
      <p className="adcs-vector-limit">
        <strong>Actuation direction constraint</strong>: if m ∥ B then τ=0, and
        torque along the magnetic field B direction cannot be produced at any
        instant.
      </p>
    </section>
  );
}
