export const equations: Record<string, string[]> = {
  '02': [
    '\\frac{GM}{r^2}=\\frac{v^2}{r}\\quad\\Longrightarrow\\quad v=\\sqrt{\\frac{GM}{r}}',
    '\\Delta E_{\\mathrm{battery}}=\\int_{t_0}^{t_1}\\left(P_{\\mathrm{charge}}-P_{\\mathrm{load}}-P_{\\mathrm{loss}}\\right)\\,\\mathrm{d}t',
    'E\\,[\\mathrm{Wh}]=\\frac{P\\,[\\mathrm{W}]\\,t\\,[\\mathrm{s}]}{3600}',
  ],
  '03': [
    '\\boldsymbol H=\\mathbf I\\boldsymbol\\omega',
    '\\mathbf I\\frac{\\mathrm{d}\\boldsymbol\\omega}{\\mathrm{d}t}+\\boldsymbol\\omega\\times(\\mathbf I\\boldsymbol\\omega)=\\boldsymbol\\tau_{\\mathrm{ext}}',
    '\\boldsymbol\\tau_{\\mathrm{mag}}=\\boldsymbol m\\times\\boldsymbol B,\\qquad |\\boldsymbol\\tau|=|\\boldsymbol m|\\,|\\boldsymbol B|\\sin\\theta',
  ],
  '04': [
    '\\lVert\\boldsymbol\\omega\\rVert<\\omega_{\\mathrm{lim}},\\qquad t\\leq T_{\\mathrm{lim}}',
  ],
  '05': [
    '\\frac{\\mathrm{d}\\boldsymbol B_{\\mathrm{body}}}{\\mathrm{d}t}\\approx-\\boldsymbol\\omega\\times\\boldsymbol B',
    '\\boldsymbol m_{\\mathrm{cmd}}=-k\\frac{\\mathrm{d}\\boldsymbol B_{\\mathrm{body}}}{\\mathrm{d}t},\\quad k>0',
    '\\boldsymbol\\tau=\\boldsymbol m\\times\\boldsymbol B',
    '\\frac{\\mathrm{d}E_{\\mathrm{rot}}}{\\mathrm{d}t}=\\boldsymbol\\tau\\cdot\\boldsymbol\\omega\\approx-k\\lVert\\boldsymbol\\omega\\times\\boldsymbol B\\rVert^2\\leq0',
  ],
};

export type EquationBlock = {
  name: string;
  purpose: string;
  formula?: string;
  statement?: string;
  notation?: string;
};

export const equationBlocks: Record<string, EquationBlock[]> = {
  '01': [
    {
      name: 'Traceable engineering claim',
      statement:
        'Claim → requirement ID → model element → verification method → result and conditions → review record',
      purpose:
        'Links the basis for a decision and its verification results so that the next reviewer can reproduce them.',
    },
  ],
  '02': [
    {
      name: 'Circular-orbit speed',
      formula: equations['02'][0],
      purpose: 'Derives circular-orbit speed from the relation between gravity and centripetal acceleration.',
      notation:
        'G: gravitational constant · M: central body mass (kg) · r: distance from centre (m) · v: speed (m/s)',
    },
    {
      name: 'Battery energy balance',
      formula: equations['02'][1],
      purpose: 'Calculates the net effect of charge, load and loss power over a period of time.',
      notation:
        'Pcharge, Pload, Ploss: power (W) · t: time (s) · ΔE: energy change (J)',
    },
    {
      name: 'Power-to-energy conversion',
      formula: equations['02'][2],
      purpose: 'Converts power and operating time into Wh, the battery energy unit.',
      notation: 'P: power (W) · t: time (s) · E: energy (Wh)',
    },
  ],
  '03': [
    {
      name: 'Angular momentum',
      formula: equations['03'][0],
      purpose: 'Links the satellite’s inertial properties and current rotational state through angular momentum.',
      notation:
        'H: angular momentum (kg·m²/s) · I: inertia matrix (kg·m²) · ω: angular velocity (rad/s)',
    },
    {
      name: 'Rigid-body rotational dynamics',
      formula: equations['03'][1],
      purpose:
        'Shows how external torque changes the satellite’s angular velocity over time.',
      notation:
        'I: inertia matrix (kg·m²) · ω: angular velocity (rad/s) · τext: external torque (N·m) · t: time (s)',
    },
    {
      name: 'Magnetic torque',
      formula: equations['03'][2],
      purpose:
        'Calculates the torque generated by the commanded magnetic dipole and the ambient magnetic field.',
      notation:
        'm: magnetic dipole (A·m²) · B: magnetic field (T) · θ: angle between the two vectors · τmag: magnetic torque (N·m)',
    },
  ],
  '04': [
    {
      name: 'Detumbling acceptance condition',
      formula: equations['04'][0],
      purpose:
        'Expresses whether the rotational state has reached the allowable limit within the specified time.',
      notation:
        'ω: angular velocity (rad/s or °/s) · ωlim: allowable limit · Tlim: completion time limit',
    },
    {
      name: 'Function-to-implementation allocation',
      statement: 'Function: rotation reduction / Implementation: sensor + OBC control SW + magnetorquer',
      purpose:
        'Distinguishes the required function from the hardware and software that perform it.',
    },
  ],
  '05': [
    {
      name: 'Body-frame magnetic-field rate',
      formula: equations['05'][0],
      purpose: 'An approximation linking the body-frame magnetic field rate to satellite rotation.',
      notation:
        'Bbody: body-frame magnetic field (T) · ω: angular velocity (rad/s) · dB/dt: magnetic field rate (T/s)',
    },
    {
      name: 'B-dot dipole command',
      formula: equations['05'][1],
      purpose: 'Commands a magnetic dipole opposite to the measured magnetic field rate.',
      notation:
        'mcmd: commanded magnetic dipole (A·m²) · k: positive control gain · dB/dt: magnetic field rate (T/s)',
    },
    {
      name: 'Magnetic torque',
      formula: equations['05'][2],
      purpose: 'Produces actuation torque from the cross product of the magnetic dipole and the ambient magnetic field.',
      notation: 'm: magnetic dipole (A·m²) · B: magnetic field (T) · τ: torque (N·m)',
    },
    {
      name: 'Rotational-energy rate',
      formula: equations['05'][3],
      purpose:
        'Shows that rotational energy does not increase under the ideal B-dot approximation.',
      notation:
        'Erot: rotational energy (J) · τ·ω: rotational power (W) · k: positive control gain',
    },
  ],
  '06': [
    {
      name: 'Fact, rule, and query',
      statement:
        'Fact: component(adcs, magnetometer).\nRule: contains(X,Y) :- component(X,Y).\nQuery: ?- contains(adcs, X).',
      purpose:
        'Shows the basic Prolog structure for querying relationships from stored facts and rules.',
    },
  ],
  '07': [
    {
      name: 'Reproducible change record',
      statement:
        'Change record = target and version + reason + impact + reproduction procedure and result + uncertainty + reviewer',
      purpose:
        'Leaves the scope, basis, results and responsibility of a change so that the next team can trace them.',
    },
  ],
};
